service: 
  name: stream-with-appsync-order-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1
  profile: cm-personal

  iamRoleStatements:
    - Effect: Allow
      Resource: '*'
      Action: 
        - dynamodb:*

package:
  include:
    - ../utils/**
    - ../models/**

functions:
  create:
    handler: api/create.handler
    events:
      - http:
          path: orders
          method: post
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true